### products index
GET http://localhost:3000/products.json

### product read/show
GET http://localhost:3000/products/2.json

### product create
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDk4NzU5Njd9.yQRJR_DPpTZp-zv1jwAMDpAgKIs9STwWt679veGHvBk
content-type: application/json

{
  "name": "test2",
  "price": 2000,
  "description": "play the bass notes",
  "images": [
    "test"
  ],
  "supplier_id": 5,
  "quantity": 5
}


### product update
PATCH http://localhost:3000/products/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDk4NzEwNDl9.r4OWBT_AkAnG_2CGyKQVBhwHZ81g0nMuwJ-i-8_duCE
content-type: application/json

{
  
}

### product delete
DELETE http://localhost:3000/products/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDk4NzEwNDl9.r4OWBT_AkAnG_2CGyKQVBhwHZ81g0nMuwJ-i-8_duCE

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "petey",
  "email": "petey@email.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jeff@email.com",
  "password": "password"
}


### order create
POST http://localhost:3000/orders.json
Authorization: Bearer 
content-type: application/json

{
  "product_id": 5,
  "quantity": 2
}


### order update
GET http://localhost:3000/orders/2.json
Authorization: Bearer 

### order index
GET http://localhost:3000/orders.json
Authorization: Bearer